In [1]:
%config IPCompleter.greedy = True

# Resumen de los datos: dimensiones y estructuras


In [2]:
import pandas as pd


In [3]:
main_path = r"C:/Users/Usuario/Documents/GitHub/python-ml-course/datasets/"
file_name = "titanic/titanic3.csv"
fullpath = main_path + file_name

In [4]:
data = pd.read_csv(fullpath)

In [5]:
data.head(10) #Permite visualizar los datos y se le puede ingresar el numero de filas que se quiere visulizar 

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
5       1         1                              Anderson, Mr. Harry    male   
6       1         1                Andrews, Miss. Kornelia Theodosia  female   
7       1         0                           Andrews, Mr. Thomas Jr    male   
8       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)  female   
9       1         0                          Artagaveytia, Mr. Ramon    male   

       age  sibsp  parch    ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0     24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2    113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2    113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2    113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2    113781  151.5500  C22 C26        S  NaN    NaN   
5  48.0000      0      0     19952   26.5500      E12        S    3    NaN   
6  63.0000      1      0     13502   77.9583       D7        S   10    NaN   
7  39.0000      0      0    112050    0.0000      A36        S  NaN    NaN   
8  53.0000      2      0     11769   51.4792     C101        S    D    NaN   
9  71.0000      0      0  PC 17609   49.5042      NaN        C  NaN   22.0   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON  
5                     New York, NY  
6                       Hudson, NY  
7                      Belfast, NI  
8              Bayside, Queens, NY  
9              Montevideo, Uruguay

In [6]:
data.shape # Devuelve (filas,columnas) 

(1309, 14)

In [7]:
data.tail() #Devuelve los ultimos datos del final del dataframe

pclass  survived                       name     sex   age  sibsp  parch  \
1304       3         0       Zabour, Miss. Hileni  female  14.5      1      0   
1305       3         0      Zabour, Miss. Thamine  female   NaN      1      0   
1306       3         0  Zakarian, Mr. Mapriededer    male  26.5      0      0   
1307       3         0        Zakarian, Mr. Ortin    male  27.0      0      0   
1308       3         0         Zimmerman, Mr. Leo    male  29.0      0      0   

      ticket     fare cabin embarked boat   body home.dest  
1304    2665  14.4542   NaN        C  NaN  328.0       NaN  
1305    2665  14.4542   NaN        C  NaN    NaN       NaN  
1306    2656   7.2250   NaN        C  NaN  304.0       NaN  
1307    2670   7.2250   NaN        C  NaN    NaN       NaN  
1308  315082   7.8750   NaN        S  NaN    NaN       NaN

In [8]:
data.columns.values #Se obtiene las cabeceras deñ dataframe en formato array

array(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype=object)

### Resumen de estadisticos basicos de las variables numericas

In [9]:
data.describe() #Permite visualizar le estadisticos basicos

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881135     0.498854     0.385027   
std       0.837836     0.486055    14.413500     1.041658     0.865560   
min       1.000000     0.000000     0.166700     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [10]:
data.dtypes #Permite saber el tipo de datos que tiene cada columna

pclass         int64
survived       int64
name          object
sex           object
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked      object
boat          object
body         float64
home.dest     object
dtype: object

### Valores Perdidos o Nulos

In [11]:
pd.isnull(data["body"]) #Para saber si hay datos nulos en la columna

0        True
1        True
2        True
3       False
4        True
        ...  
1304    False
1305     True
1306    False
1307     True
1308     True
Name: body, Length: 1309, dtype: bool

In [12]:
pd.notnull(data["body"]) #Para saber si no hay datos nulos en la columna

0       False
1       False
2       False
3        True
4       False
        ...  
1304     True
1305    False
1306     True
1307    False
1308    False
Name: body, Length: 1309, dtype: bool

In [17]:
#SUMANDO NULOS
pd.isnull(data["body"]).values.ravel().sum() 
# ravel() es para hacer que todo los datos puedan estar en un array y no en una columna
# sum() se le puede aplicar esta funcion para sumar los los cuales son TRUE = 1

1188

In [19]:
#SUMANDO NO NULOS
pd.notnull(data["body"]).values.ravel().sum()

121

In [20]:
# tanto flatten como ravel 'aplanan' una matriz
import numpy as np
matriz = np.array(((1,2,3),(4,5,6),(7,8,9)))
print(matriz)
print(matriz.flatten())
print(matriz.ravel())
matriz.flatten()[0]=100
print("matriz con flatten no modifica original \n", matriz)
matriz.ravel()[0]=100
print("matriz con ravel SI modifica el original \n", matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
matriz con flatten no modifica original 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
matriz con ravel SI modifica el original 
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]


Los valores que faltan de un data set pueden venir por dos razones:
* Extraccion de los datos
* Recoleccion de los datos

### Borrado de valores que faltan

In [25]:
data.dropna(axis=0, how="all")  #axis=0 borra filas, axis=1 borra columnas
#how = "all" elimina si todos los elementos de la fila o columna son NaN
#how = "any" elimina si algun valor de la fila o columna es NaN
#dropna nos ayuda a eliminar valores NaN

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

In [26]:
data2 = data.copy()

In [27]:
data2.dropna(axis=0, how="any")

Empty DataFrame
Columns: [pclass, survived, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, boat, body, home.dest]
Index: []

### Cómputo de los valores faltantes

In [29]:
#Llenando los valores faltantes con cero
data3 = data.copy()

In [31]:
data3.fillna(0) #Reemplaza todo los valores faltantes con el valor 0

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S    0   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S    0   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S    0   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542        0        C    0   
1305  female   0.0000      1      0    2665   14.4542        0        C    0   
1306    male  26.5000      0      0    2656    7.2250        0        C    0   
1307    male  27.0000      0      0    2670    7.2250        0        C    0   
1308    male  29.0000      0      0  315082    7.8750        0        S    0   

       body                        home.dest  
0       0.0                     St Louis, MO  
1       0.0  Montreal, PQ / Chesterville, ON  
2       0.0  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       0.0  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                                0  
1305    0.0                                0  
1306  304.0                                0  
1307    0.0                                0  
1308    0.0                                0  

[1309 rows x 14 columns]

In [32]:
data4 = data.copy()

In [34]:
data4.fillna("Desconocido") #Se llena los valores faltantes con la palaba "Desconocido"

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex          age  sibsp  parch  ticket      fare        cabin  \
0     female         29.0      0      0   24160  211.3375           B5   
1       male       0.9167      1      2  113781    151.55      C22 C26   
2     female          2.0      1      2  113781    151.55      C22 C26   
3       male         30.0      1      2  113781    151.55      C22 C26   
4     female         25.0      1      2  113781    151.55      C22 C26   
...      ...          ...    ...    ...     ...       ...          ...   
1304  female         14.5      1      0    2665   14.4542  Desconocido   
1305  female  Desconocido      1      0    2665   14.4542  Desconocido   
1306    male         26.5      0      0    2656     7.225  Desconocido   
1307    male         27.0      0      0    2670     7.225  Desconocido   
1308    male         29.0      0      0  315082     7.875  Desconocido   

     embarked         boat         body                        home.dest  
0           S            2  Desconocido                     St Louis, MO  
1           S           11  Desconocido  Montreal, PQ / Chesterville, ON  
2           S  Desconocido  Desconocido  Montreal, PQ / Chesterville, ON  
3           S  Desconocido        135.0  Montreal, PQ / Chesterville, ON  
4           S  Desconocido  Desconocido  Montreal, PQ / Chesterville, ON  
...       ...          ...          ...                              ...  
1304        C  Desconocido        328.0                      Desconocido  
1305        C  Desconocido  Desconocido                      Desconocido  
1306        C  Desconocido        304.0                      Desconocido  
1307        C  Desconocido  Desconocido                      Desconocido  
1308        S  Desconocido  Desconocido                      Desconocido  

[1309 rows x 14 columns]

In [35]:
data5 = data.copy()

In [36]:
data5["body"].fillna(0) #Se puede reemplazar los valores de una columna en vez de todo el Dataframe

0         0.0
1         0.0
2         0.0
3       135.0
4         0.0
        ...  
1304    328.0
1305      0.0
1306    304.0
1307      0.0
1308      0.0
Name: body, Length: 1309, dtype: float64

In [37]:
data5["home.dest"].fillna("Desconocido") #Se reemplaza los valores de una columna con la palabra "Desconocido"

0                          St Louis, MO
1       Montreal, PQ / Chesterville, ON
2       Montreal, PQ / Chesterville, ON
3       Montreal, PQ / Chesterville, ON
4       Montreal, PQ / Chesterville, ON
                     ...               
1304                        Desconocido
1305                        Desconocido
1306                        Desconocido
1307                        Desconocido
1308                        Desconocido
Name: home.dest, Length: 1309, dtype: object

In [38]:
data5.tail() #Se observa que los cambios no se han hecho efectivo en el dataframe  
#Porque no se han reemplazado los valores

pclass  survived                       name     sex   age  sibsp  parch  \
1304       3         0       Zabour, Miss. Hileni  female  14.5      1      0   
1305       3         0      Zabour, Miss. Thamine  female   NaN      1      0   
1306       3         0  Zakarian, Mr. Mapriededer    male  26.5      0      0   
1307       3         0        Zakarian, Mr. Ortin    male  27.0      0      0   
1308       3         0         Zimmerman, Mr. Leo    male  29.0      0      0   

      ticket     fare cabin embarked boat   body home.dest  
1304    2665  14.4542   NaN        C  NaN  328.0       NaN  
1305    2665  14.4542   NaN        C  NaN    NaN       NaN  
1306    2656   7.2250   NaN        C  NaN  304.0       NaN  
1307    2670   7.2250   NaN        C  NaN    NaN       NaN  
1308  315082   7.8750   NaN        S  NaN    NaN       NaN

In [40]:
#Reemplazando los valores en el DataFrame
data5["body"] = data5["body"].fillna(0)
data5["home.dest"] = data5["home.dest"].fillna("Desconocido")

In [42]:
data5.head(20)

pclass  survived                                               name  \
0        1         1                      Allen, Miss. Elisabeth Walton   
1        1         1                     Allison, Master. Hudson Trevor   
2        1         0                       Allison, Miss. Helen Loraine   
3        1         0               Allison, Mr. Hudson Joshua Creighton   
4        1         0    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
5        1         1                                Anderson, Mr. Harry   
6        1         1                  Andrews, Miss. Kornelia Theodosia   
7        1         0                             Andrews, Mr. Thomas Jr   
8        1         1      Appleton, Mrs. Edward Dale (Charlotte Lamson)   
9        1         0                            Artagaveytia, Mr. Ramon   
10       1         0                             Astor, Col. John Jacob   
11       1         1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)   
12       1         1                      Aubart, Mme. Leontine Pauline   
13       1         1                       Barber, Miss. Ellen "Nellie"   
14       1         1               Barkworth, Mr. Algernon Henry Wilson   
15       1         0                                Baumann, Mr. John D   
16       1         0                           Baxter, Mr. Quigg Edmond   
17       1         1    Baxter, Mrs. James (Helene DeLaudeniere Chaput)   
18       1         1                              Bazzani, Miss. Albina   
19       1         0                               Beattie, Mr. Thomson   

       sex      age  sibsp  parch    ticket      fare    cabin embarked boat  \
0   female  29.0000      0      0     24160  211.3375       B5        S    2   
1     male   0.9167      1      2    113781  151.5500  C22 C26        S   11   
2   female   2.0000      1      2    113781  151.5500  C22 C26        S  NaN   
3     male  30.0000      1      2    113781  151.5500  C22 C26        S  NaN   
4   female  25.0000      1      2    113781  151.5500  C22 C26        S  NaN   
5     male  48.0000      0      0     19952   26.5500      E12        S    3   
6   female  63.0000      1      0     13502   77.9583       D7        S   10   
7     male  39.0000      0      0    112050    0.0000      A36        S  NaN   
8   female  53.0000      2      0     11769   51.4792     C101        S    D   
9     male  71.0000      0      0  PC 17609   49.5042      NaN        C  NaN   
10    male  47.0000      1      0  PC 17757  227.5250  C62 C64        C  NaN   
11  female  18.0000      1      0  PC 17757  227.5250  C62 C64        C    4   
12  female  24.0000      0      0  PC 17477   69.3000      B35        C    9   
13  female  26.0000      0      0     19877   78.8500      NaN        S    6   
14    male  80.0000      0      0     27042   30.0000      A23        S    B   
15    male      NaN      0      0  PC 17318   25.9250      NaN        S  NaN   
16    male  24.0000      0      1  PC 17558  247.5208  B58 B60        C  NaN   
17  female  50.0000      0      1  PC 17558  247.5208  B58 B60        C    6   
18  female  32.0000      0      0     11813   76.2917      D15        C    8   
19    male  36.0000      0      0     13050   75.2417       C6        C    A   

     body                        home.dest  
0     0.0                     St Louis, MO  
1     0.0  Montreal, PQ / Chesterville, ON  
2     0.0  Montreal, PQ / Chesterville, ON  
3   135.0  Montreal, PQ / Chesterville, ON  
4     0.0  Montreal, PQ / Chesterville, ON  
5     0.0                     New York, NY  
6     0.0                       Hudson, NY  
7     0.0                      Belfast, NI  
8     0.0              Bayside, Queens, NY  
9    22.0              Montevideo, Uruguay  
10  124.0                     New York, NY  
11    0.0                     New York, NY  
12    0.0                    Paris, France  
13    0.0                      Desconocido  
14    0.0                    Hessle, Yorks  
15    0.0                  

#### RELLENANDO LOS VALORES FALTANTES CON METODOS ESTADISTICOS BASICOS

In [48]:
data5["age"].isnull().values.ravel().sum()

263

In [49]:
pd.isnull(data["age"]).values.ravel().sum()

263

In [50]:
data["age"].fillna(data["age"].mean()) #Los valores NaN han sido reemplazados por el promedio de valores de la columna "age"


0       29.000000
1        0.916700
2        2.000000
3       30.000000
4       25.000000
          ...    
1304    14.500000
1305    29.881135
1306    26.500000
1307    27.000000
1308    29.000000
Name: age, Length: 1309, dtype: float64

In [52]:
data["age"][1305]

nan

In [53]:
data5["age"].fillna(method="ffill") #Con el metodo ffill los valores NaN se reemplazan con el valor siguiente proximo

0       29.0000
1        0.9167
2        2.0000
3       30.0000
4       25.0000
         ...   
1304    14.5000
1305    14.5000
1306    26.5000
1307    27.0000
1308    29.0000
Name: age, Length: 1309, dtype: float64

In [55]:
data5["age"].fillna(method="backfill") #con el metodo backfill los valores NaN se reemplazan con el valor anterior proximo

0       29.0000
1        0.9167
2        2.0000
3       30.0000
4       25.0000
         ...   
1304    14.5000
1305    26.5000
1306    26.5000
1307    27.0000
1308    29.0000
Name: age, Length: 1309, dtype: float64

### Creacion de Variables dummy
#### Aplicado a variables categoricas 

In [56]:
data["sex"]

0       female
1         male
2       female
3         male
4       female
         ...  
1304    female
1305    female
1306      male
1307      male
1308      male
Name: sex, Length: 1309, dtype: object

In [57]:
dummy_sex = pd.get_dummies(data["sex"], prefix="sex")

In [59]:
dummy_sex.head(12)

sex_female  sex_male
0            1         0
1            0         1
2            1         0
3            0         1
4            1         0
5            0         1
6            1         0
7            0         1
8            1         0
9            0         1
10           0         1
11           1         0

In [62]:
column_name = data.columns.values.tolist()
column_name

['pclass',
 'survived',
 'name',
 'sex',
 'age',
 'sibsp',
 'parch',
 'ticket',
 'fare',
 'cabin',
 'embarked',
 'boat',
 'body',
 'home.dest']

In [64]:
data.drop(["sex"], axis=1) # pd.drop() puede eliminar la columna entera
# axis=1 indica que es una columna y no una fila
# Con esto el DataFrame original no se afecta 

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

          age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0     29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1      0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2      2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3     30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4     25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
...       ...    ...    ...     ...       ...      ...      ...  ...    ...   
1304  14.5000      1      0    2665   14.4542      NaN        C  NaN  328.0   
1305      NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   
1306  26.5000      0      0    2656    7.2250      NaN        C  NaN  304.0   
1307  27.0000      0      0    2670    7.2250      NaN        C  NaN    NaN   
1308  29.0000      0      0  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 13 columns]

In [65]:
data = data.drop(["sex"], axis=1) #Con eso si modificamos el DataFrame original

In [67]:
pd.concat([data, dummy_sex], axis=1) #Con pd.concat unimos DataFrame por columnas (axis=1)

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

          age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0     29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1      0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2      2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3     30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4     25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
...       ...    ...    ...     ...       ...      ...      ...  ...    ...   
1304  14.5000      1      0    2665   14.4542      NaN        C  NaN  328.0   
1305      NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   
1306  26.5000      0      0    2656    7.2250      NaN        C  NaN  304.0   
1307  27.0000      0      0    2670    7.2250      NaN        C  NaN    NaN   
1308  29.0000      0      0  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  sex_female  sex_male  
0                        St Louis, MO           1         0  
1     Montreal, PQ / Chesterville, ON           0         1  
2     Montreal, PQ / Chesterville, ON           1         0  
3     Montreal, PQ / Chesterville, ON           0         1  
4     Montreal, PQ / Chesterville, ON           1         0  
...                               ...         ...       ...  
1304                              NaN           1         0  
1305                              NaN           1         0  
1306                              NaN           0         1  
1307                              NaN           0         1  
1308                              NaN           0         1  

[1309 rows x 15 columns]

In [70]:
#Creando una funcion que me crea dummies a partir de una columna categorica 

def createDummies(df, var_name):
        dummy = pd.get_dummies(df[var_name], prefix=var_name)
        df = df.drop(var_name, axis=1)
        df = pd.concat([df, dummy], axis = 1)
        return df

In [71]:
createDummies(data3, "sex")

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

          age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0     29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1      0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2      2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3     30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4     25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
...       ...    ...    ...     ...       ...      ...      ...  ...    ...   
1304  14.5000      1      0    2665   14.4542      NaN        C  NaN  328.0   
1305      NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   
1306  26.5000      0      0    2656    7.2250      NaN        C  NaN  304.0   
1307  27.0000      0      0    2670    7.2250      NaN        C  NaN    NaN   
1308  29.0000      0      0  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  sex_female  sex_male  
0                        St Louis, MO           1         0  
1     Montreal, PQ / Chesterville, ON           0         1  
2     Montreal, PQ / Chesterville, ON           1         0  
3     Montreal, PQ / Chesterville, ON           0         1  
4     Montreal, PQ / Chesterville, ON           1         0  
...                               ...         ...       ...  
1304                              NaN           1         0  
1305                              NaN           1         0  
1306                              NaN           0         1  
1307                              NaN           0         1  
1308                              NaN           0         1  

[1309 rows x 15 columns]