# Regresión Lineal en Python
### El pauete scikit-learn para regresión lineal y la selección de rasgos - Variables Predictoras

In [1]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [3]:
feature_cols = ["TV", "Radio", "Newspaper"] #Seleccionando la columnas
#Que representan las variables predictivas

In [4]:
X = data[feature_cols] #Variables predictoras seleccionadas del Dataframe
Y = data["Sales"] #Variable a Predecir seleecionada del Dataset

In [5]:
estimador = SVR(kernel="linear") #Con SVR determinamos el metodo linear -

#Con RFE determinamos el numero de variables predictoras = 2 y los pasos=1
selector = RFE(estimador, n_features_to_select=2, step=1) 

#Con el metodo .fit(X,Y) ajustamos la regresion añadiendo X(variables predictoras)
# y Y(Variable a determinar)
selector = selector.fit(X,Y)

In [6]:
selector.support_  #.support_  me indica que variables predictoras fueron 
#escogidas para la regresion lineal

array([ True,  True, False])

In [7]:
selector.ranking_ #.ranking_ me indica el orden de prioridad de las varibles
#predictoras para la regresion lineal

array([1, 1, 2])

### Hallando el modelo que permita predecir con Sklearn

In [8]:
from sklearn.linear_model import LinearRegression #Este paquete determina
#Todo lo que se necesita para la regresion lineal

In [9]:
x_pred = X[["TV", "Radio"]] #Determinamos las variables predictoras entre []

In [10]:
lm = LinearRegression() #Determiamos un elemento de clase LinearRegression()
lm.fit(x_pred, Y) #Ajustqmos lo anterior a las condiciones de x_pred e Y

LinearRegression()

In [11]:
lm.intercept_ #Determinamos el parametro alpha con .intercept_

2.9210999124051362

In [12]:
lm.coef_ #Determinamos los parametros beta con .coef_

array([0.04575482, 0.18799423])

In [13]:
lm.score(x_pred, Y) #Determinamos el R2 con .score() e ingreamos x_pred e Y

0.8971942610828957